[pytest]
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated:DeprecationWarning
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
    ignore:'audioop' is deprecated:DeprecationWarning
    ignore:Couldn't find ffmpeg or avconv:RuntimeWarning
    ignore:Couldn't find ffprobe or avprobe:RuntimeWarning
    ignore::DeprecationWarning:fastapi.*
    ignore::DeprecationWarning:starlette.*
    ignore::DeprecationWarning:pydub.*
    ignore::RuntimeWarning:pydub.*
