[pytest]
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated
    ignore:The anyio.abc.BlockingPortal alias is deprecated
    ignore:'audioop' is deprecated
    ignore:Couldn't find ffmpeg or avconv
    ignore:Couldn't find ffprobe or avprobe
    ignore:Requested Pretrainer collection using symlinks on Windows
    ignore:Using SYMLINK strategy on Windows for fetching potentially requires elevated privileges
    ignore:The `local_dir_use_symlinks` argument is deprecated
    ignore::DeprecationWarning:fastapi.*
    ignore::DeprecationWarning:starlette.*
    ignore::DeprecationWarning:pydub.*
    ignore::RuntimeWarning:pydub.*
